<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'uz' => '',
    'Bosh sahifa' => 'Home',
    'Darsliklar' => 'Textbooks',
    'Biz haqimizda' => 'About Us',
    'Aloqa' => 'Contact',
    'Chiqish' => 'Exit',
    'Sinflar' => 'Classes',
    'Bo`limlar' => 'Sections',
    'Mavzulashtirilgan Testlar' => 'Thematic Tests',
    'Variant testlar' => 'Option tests',
    'Mavzular' => 'Topics',
    'Test' => 'Test',
    'Testlar' => 'Tests',
    'Testni tugatish' => 'End Test',
    'Testni boshlash' => 'Start test',
    'O`zbek tilida Testni boshlash' => 'Start the Test in English',
    'Testni tugatasizmi' => 'Will you finish the test',
    'To`lov' => 'Payment',
    'Natija' => 'The result',
    'To`g`ri' => 'Correct',
    'Xato' => 'Error',
    'Qoldirilgan' => 'Abandoned',
    'Oldingi' => 'Previous',
    'Keyingi' => 'Next',
    'Soat' => 'Hour',
    'Daqiqa' => 'Minute',
    'Soniya' => 'Sonia',
    'Apilatsiya' => 'Apilation',
    'Bu savol haqida' => 'About this question',
    'Yuborish' => 'Send',
    'Bekor qilish' => 'Cancel',
    'Yangiliklar' => 'News',
    'Batafsil' => 'More',
    'Yana yangiliklar' => 'More news',
    'Yana videolar' => 'More video',
    'Hammasi shular' => 'That`s all',
    'Baham ko`ring:' => 'Share:',
    'Maktab darsliklari' => 'School textbooks',
    'Atlaslar' => 'Atlases',
    'Prizintatsiyalar' => 'Presentation',
    '{0,number} sinf' => 'Class {0,number}',
    'Kitoblar' => 'Books',
    'Nomi'=>'Name',
    'Hajmi'=>'Size',
    'Chop etilgan sana'=>'Date of publication',
    'Muallif'=>'Author',
    'Til'=>'Lang',
    'Fayl turi'=>'File type',
    'Qisqacha'=>'In short',
    'Fayl'=>'File',
    'Balki, siz boshqa tillarda ma`lumot topaolarsiz'=>'You may find information in other languages',
    'Video darslar'=>'Video lessons',
    'Ma`lumotlar'=>'Information',
    'Rasmlar'=>'Pictures',
    'Kun tarixi'=>'History of the day',
    'Kirish'=>'Enter',
    'Ro`yhatdan o`tish'=>'Registration',
    'Izohlar' => 'Comments',
    'Shaxsiy kabinet' => 'Personal cabinet',
    'So`m' => 'Sum',
    'Qolgan testlar soni' => 'Number of residual tests',
    'Tugash vaqti' => 'End time',
    'Hisobni to`dirish' => 'replenish the account',
    'Saqlash'=>'Save',
    ];




































