<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'uz' => '',
    'Bosh sahifa' => 'Home',
    'Biz haqimizda' => 'About Us',
    'Aloqa' => 'Contact',
    'Chiqish' => 'Exit',
    'Sinflar' => 'Classes',
    'Bo`limlar' => 'Sections',
    'Yuborish' => 'Send',
    'Bekor qilish' => 'Cancel',
    'Yangiliklar' => 'News',
    'Batafsil' => 'More',
    'Yana yangiliklar' => 'More news',
    'Yana videolar' => 'More video',
    'Hammasi shular' => 'That`s all',
    'Baham ko`ring:' => 'Share:',
    'Maktab darsliklari' => 'School textbooks',
    'Atlaslar' => 'Atlases',
    'Prizintatsiyalar' => 'Presentation',
    'Nomi'=>'Name',
    'Hajmi'=>'Size',
    'Til'=>'Lang',
    'Qisqacha'=>'In short',
    'Fayl'=>'File',
    'Ma`lumotlar'=>'Information',
    'Rasmlar'=>'Pictures',
    'Kirish'=>'Enter',
    'Ro`yhatdan o`tish'=>'Registration',
    'Izohlar' => 'Comments',
    'Shaxsiy kabinet' => 'Personal cabinet',
    'Saqlash'=>'Save',
    'Murabbiylar'=>'Coaches',
    'Biz bilan bog`lanish' => 'Contact us',
    'Manzil'=>'Address',
];




































