<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'uz' => 'ru',
    'Bosh sahifa' => 'Домой',
    'Darsliklar' => 'Учебники',
    'Biz haqimizda' => 'О нас',
    'Aloqa' => 'Контакть',
    'Chiqish' => 'Выход',
    'Sinflar' => 'Классы',
    'Bo`limlar' => 'Разделы',
    'Mavzulashtirilgan Testlar' => 'Тематические тесты',
    'Variant testlar' => 'Вариантные тесты',
    'Mavzular' => 'Темы',
    'Test' => 'Тесты',
    'Testlar' => 'Тесты',
    'Testni tugatish' => 'Завершить тест',
    'Testni boshlash' => 'Начать тест',
    'O`zbek tilida Testni boshlash' => 'Начать тест на русском языке',
    'Testni tugatasizmi' => 'Вы хотите закончить тест?',
    'To`lov' => 'Оплата',
    'Natija' => 'Результат',
    'To`g`ri' => 'Правильный',
    'Xato' => 'Ошибка',
    'Qoldirilgan' => 'Заброшенный',
    'Oldingi' => 'Предыдущий',
    'Keyingi' => 'Следующий',
    'Soat' => 'Час',
    'Daqiqa' => 'Минуты',
    'Soniya' => 'Секунды',
    'Apilatsiya' => 'Апиляция',
    'Bu savol haqida' => 'Это о вопросе',
    'Yuborish' => 'Отправить',
    'Bekor qilish' => 'Отмена',
    'Yangiliklar' => 'Новости',
    'Batafsil' => 'Больше',
    'Yana yangiliklar' => 'Больше новости',
    'Yana videolar' => 'Больше ролики',
    'Hammasi shular' => 'Вот и все',
    'Baham ko`ring:' => 'Доля:',
    'Maktab darsliklari' => 'Школьные учебники',
    'Atlaslar' => 'Атласы',
    'Prizintatsiyalar' => 'Презентация',
    '{0,number} sinf' => 'Класс {0,number}',
    'Kitoblar' => 'Книги',
    'Nomi'=>'Название',
    'Hajmi'=>'Размер',
    'Chop etilgan sana'=>'Дата публикации',
    'Muallif'=>'Автор',
    'Til'=>'Язык',
    'Fayl turi'=>'Тип файла',
    'Qisqacha'=>'Информация',
    'Fayl'=>'файл',
    'Balki, siz boshqa tillarda ma`lumot topaolarsiz'=>'Вы можете найти информацию на других языках',
    'Video darslar'=>'Видео уроки',
    'Ma`lumotlar'=>'Информация',
    'Rasmlar'=>'Картинки',
    'Kun tarixi'=>'История дня',
    'Kirish'=>'Войти',
    'Ro`yhatdan o`tish'=>'Регистрация',
    'Izohlar' => 'Комментарии',
    'Shaxsiy kabinet' => 'Личный кабинет',
    'So`m' => 'Сум',
    'Qolgan testlar soni' => 'Количество остаточных тестов',
    'Tugash vaqti' => 'Время окончания',
    'Hisobni to`dirish' => 'Пополнить счет',
    'Saqlash'=>'Сохранить',


];
